version: '2'


services:

  apiscraper:
    container_name: apiscraper
    build:
#      args:
#        gitversion: 69e2af3cec804688c01c7c1b85a130997ca6107b
      context: .
      dockerfile: Dockerfile.compose
    volumes:
       - ./config.py:/tesla-apiscraper/config.py
       - ./apiscraper.log:/tesla-apiscraper/apiscraper.log
    ports:
      - "8023:8023"
    restart: on-failure:5
#    depends_on:
#      - influxdb
