{
 "title": "Charging",
 "tags": [ "tesla" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vehicle_name",
    "query": "select distinct(display_name) from (select * from charge_state)"
   },
   { "name": "rangeunit", "query": "${VAR_RANGEUNIT}" },
   { "name": "rangefactor", "query": "1.60934" }
  ]
 },
 "panels": [
  {
   "title": "Range",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "ideal_battery_range" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*$rangefactor" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Range",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "query": "SELECT last(\"est_battery_range\") FROM \"charge_state\" WHERE (\"metric\" = 'est_battery_range')  AND $timeFilter",
     "select": [
      [
       { "params": [ "est_battery_range" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*$rangefactor" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Range",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "query": "SELECT last(\"battery_range\") *$rangefactor FROM \"charge_state\" WHERE (\"metric\" = 'battery_range') AND $timeFilter",
     "select": [
      [
       { "params": [ "battery_range" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*$rangefactor" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Energy added",
   "type": "singlestat",
   "description": "Energy added on last Charge",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 0 },
   "format": "kwatth",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "charge_energy_added" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Time to Full at current Rate",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 0 },
   "format": "h",
   "valueName": "current",
   "targets": [
    {
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "time_to_full_charge" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "AC Charger Phases",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "charger_phases" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "AC Charger Actual Current",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "format": "amp",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "charger_actual_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charger Voltage",
   "type": "singlestat",
   "description": "Voltage supplied by Charger",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 2 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "measurement": "charge_state",
     "query": "SELECT last(\"charger_voltage\") FROM \"charge_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) ",
     "select": [
      [
       { "params": [ "charger_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "charger_voltage" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charger Voltage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 2 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "charger_voltage",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "charger_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "singlestat",
   "description": "Current Battery Level",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "battery_level",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "linear" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "query": "SELECT mean(\"battery_level\") FROM \"charge_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter GROUP BY time($__interval) fill(linear)",
     "select": [
      [
       { "params": [ "battery_level" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "battery_level" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "alias": "charge_limit_soc",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "query": "SELECT mean(\"charge_limit_soc\") FROM \"charge_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter GROUP BY time($__interval) fill(previous)",
     "select": [
      [
       { "params": [ "charge_limit_soc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "charge_limit_soc" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charger Power",
   "type": "singlestat",
   "description": "Power supplied by Charger.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 12 },
   "format": "kwatt",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "charger_power" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Chargerpower vs Batterypower",
   "type": "graph",
   "gridPos": { "h": 5, "w": 20, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "kwatt" }
   ],
   "targets": [
    {
     "alias": "charger_power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "charge_state",
     "select": [
      [
       { "params": [ "charger_power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    },
    {
     "alias": "power",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "drive_state",
     "select": [
      [
       { "params": [ "power" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Charger Events",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 17 },
   "targets": [
    {
     "measurement": "charge_state",
     "query": "SELECT \"charging_state\" FROM \"charge_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter-5d",
     "select": [
      [
       { "params": [ "charging_state" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "charging_state" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Heater",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 21 },
   "targets": [
    {
     "alias": "Battery Heater",
     "measurement": "charge_state",
     "query": "SELECT \"battery_heater_on\" FROM \"charge_state\" WHERE (\"display_name\" =~ /^$vehicle_name$/) AND $timeFilter-5d",
     "select": [
      [
       { "params": [ "battery_heater_on" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "metric", "operator": "=", "value": "battery_heater_on" },
      { "condition": "AND", "key": "display_name", "operator": "=~", "value": "/^$vehicle_name$/" }
     ]
    }
   ]
  }
 ]
}